.TH "command_mapping" 3 "Sun Jun 5 2016" "pictDB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
command_mapping \- Struct représentant l'association commande-nom de fonction\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBline_name\fP"
.br
.ti -1c
.RI "command \fBline_cmd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct représentant l'association commande-nom de fonction\&. 

structure qui associe a la chaine de caractère reçue par la ligne de commande, la fonction do_COMMAND_cmd associée\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for pictDB from the source code\&.
