.TH "db_delete.c" 3 "Sun Jun 5 2016" "pictDB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
db_delete.c \- pictDB library: do_delete implementation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pictDB\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdo_delete\fP (const char *pictID, struct \fBpictdb_file\fP *\fBpictdb_file\fP)"
.br
.RI "\fIDeletes the image from the database given in argument\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
pictDB library: do_delete implementation\&. 


.PP
\fBAuthor:\fP
.RS 4
Cédric Viaccoz 
.PP
Matteo Giorla 
.RE
.PP
\fBDate:\fP
.RS 4
11 Avr 2016 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int do_delete (const char * pictID, struct \fBpictdb_file\fP * db_file)"

.PP
Deletes the image from the database given in argument\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpictID\fP the name of the picture wanted to be erased \&. 
.br
\fIdb_file\fP In memory structure with header and metadata\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
error code as defined in \fBerror\&.h\fP if anything went wrong, 0 otherwise\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for pictDB from the source code\&.
