.TH "db_list.c" 3 "Sun Jun 5 2016" "pictDB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
db_list.c \- pictDB: do_list implementation  

.SH SYNOPSIS
.br
.PP
\fC#include 'pictDB\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <json-c/json\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBdo_list\fP (struct \fBpictdb_file\fP const *\fBpictdb_file\fP, enum \fBdo_list_mode\fP \fBdo_list_mode\fP)"
.br
.RI "\fIDisplays (on stdout or json) pictDB metadata\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
pictDB: do_list implementation 


.PP
\fBAuthor:\fP
.RS 4
Mia Primorac 
.PP
Cédric Viaccoz 
.PP
Matteo Giorla 
.RE
.PP
\fBDate:\fP
.RS 4
14 Mar 2016 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "const char* do_list (struct \fBpictdb_file\fP const * pictdb_file, enum \fBdo_list_mode\fP \fBdo_list_mode\fP)"

.PP
Displays (on stdout or json) pictDB metadata\&. Do List\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for pictDB from the source code\&.
