.TH "error.h" 3 "Sun Jun 5 2016" "pictDB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
error.h \- pictDB library error codes and messages\&.  

.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBerror_codes\fP { \fBERR_IO\fP = 1, \fBERR_OUT_OF_MEMORY\fP, \fBERR_NOT_ENOUGH_ARGUMENTS\fP, \fBERR_INVALID_FILENAME\fP, \fBERR_INVALID_COMMAND\fP, \fBERR_INVALID_ARGUMENT\fP, \fBERR_MAX_FILES\fP, \fBERR_RESOLUTIONS\fP, \fBERR_INVALID_PICID\fP, \fBERR_FULL_DATABASE\fP, \fBERR_FILE_NOT_FOUND\fP, \fBNOT_IMPLEMENTED\fP, \fBERR_DUPLICATE_ID\fP, \fBERR_VIPS\fP, \fBERR_DEBUG\fP }"
.br
.RI "\fIpictDB library internal error codes\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char *const \fBERROR_MESSAGES\fP []"
.br
.RI "\fIpictDB library internal error messages\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
pictDB library error codes and messages\&. 


.PP
\fBAuthor:\fP
.RS 4
Mia Primorac 
.RE
.PP
\fBDate:\fP
.RS 4
2 Nov 2015 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for pictDB from the source code\&.
